services:

#---------------------------------BACKEND--------------------------------
# available on port 3000 inside docker
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - ft_transcendence
    volumes:
      - sqlite_data:/db
    restart: always

#--------------------------------FRONTEND--------------------------------

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BASE_API_URL=${BASE_API_URL}
        - BASE_WSS_URL=${BASE_WSS_URL}
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    networks:
      - ft_transcendence
    volumes:
      - frontend_data:/usr/src/app/public
    depends_on:
      - backend

#---------------------------------NGINX----------------------------------

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:443"
    networks:
      - ft_transcendence
    volumes:
      - frontend_data:/usr/share/nginx/html
    depends_on:
      - frontend
    restart: always
    
#--------------------------------VOLUMES---------------------------------

volumes:
  sqlite_data:
    driver: local
  frontend_data:
    driver: local

#--------------------------------NETWORKS--------------------------------

networks:
  ft_transcendence:
    name: ft_transcendence

#--------------------------------SECRETS---------------------------------