server {
    listen 443 ssl;
    listen [::]:443 ssl; # ipv6
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/transcend.crt;
    ssl_certificate_key /etc/nginx/ssl/transcend.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html; # single page application
    }

    location /api/ {
        proxy_pass http://backend:3000/api/;
        proxy_set_header X-Real-IP $remote_addr; # pass the client's IP address
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # pass IP address of any intermediate proxies
        proxy_set_header Host $host; # pass original host header from client request
        proxy_set_header X-Forwarded-Proto $scheme; # inform backend if client request was made over http or https
        proxy_set_header X-Original-Uri $request_uri;  # preserve full URI
        access_log /var/log/nginx/proxy.log;
    }

    location /ws/ {
        proxy_pass http://backend:3000/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade; # required header to switch from http to websocket
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location /uploads/ {
        proxy_pass http://backend:3000/uploads/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Original-Uri $request_uri;
        access_log /var/log/nginx/uploads_proxy.log;
    }
}
